# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d008e7c03bbeaff7c9cd6b6536f6d94f1b3dc9527a6e59ddce86d2c76bde21460374837ee4a2b710c49d56a63883474bd21c02c6797cd0ae7d0fdfd868bdbd

test:
  secret_key_base: 91fc552701da370e5cf7175066b3d7126aad99d69fbb2ccc3e596eb9da48262233a5abee28f0c63e319be38dd895515181f9d6f394117c0d8f2403945b7a42f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
